version: '3.8'

services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - MODULE_ENV=production

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
